from os import environ

FIREBASE_API_KEY = environ.get('FIREBASE_API_KEY')
FIREBASE_AUTH_DOMAIN = environ.get('FIREBASE_AUTH_DOMAIN')
FIREBASE_DATABASE_URL = environ.get('FIREBASE_DATABASE_URL')
FIREBASE_STORAGE_BUCKET = environ.get('FIREBASE_STORAGE_BUCKET')
FIREBASE_CREDENTIAL = environ.get('FIREBASE_CREDENTIAL')